version: '2'

services:
  php:
    build: php
    container_name: $PHP_CONTAINER_NAME
    volumes:
      - './config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - ..:$PHP_ROOT_DIR
    ports:
      - 8008:8008

  elk:
    build: elk
    container_name: elk
    user: root
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./data/log:/var/log/import
      - ./elk/logstash/logstash.yml:/opt/logstash/config/logstash.yml
      - ./elk/logstash/conf.d:/etc/logstash/conf.d
      - ./data/elasticsearch:/var/lib/elasticsearch
      - ./elk/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elk/security/elastic-certificates.p12:/opt/elasticsearch/config/elastic-certificates.p12
      - ./elk/kibana/kibana.yml:/opt/kibana/config/kibana.yml
    depends_on:
      - apache

  apache:
    image: httpd:2.4
    container_name: $APACHE_CONTAINER_NAME
    environment:
      VHOST_BASE_DOC_ROOT: $PHP_ROOT_DIR
      VHOST_SERVER_NAME: $APACHE_SERVER_NAME
      VHOST_PHP_HOST: $PHP_CONTAINER_NAME
    ports:
      - 80:80
    volumes:
      - ./config/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./data/log:/var/log
      - ..:$PHP_ROOT_DIR
    depends_on:
      - php

  db:
    image: mysql
    container_name: $DB_CONTAINER_NAME
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: $DB_ADMIN_CONTAINER_NAME
    environment:
      PMA_HOST: $DB_CONTAINER_NAME
      PMA_PORT: $DB_PORT
      PMA_USER: root
      PMA_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - 8080:80
    depends_on:
      - db



  dockerize:
    image: jwilder/dockerize
